%YAML:1.2
---
OccMap:
  # resolution: 0.03 # (unit: m)
  # map_x: 40 # (unit: m)
  # map_y: 40 # (unit: m)
  # map_z: 15 # (unit: m)
  # voxel_depth: 2
  # block_depth: 3
  # resolution: 0.05 # (unit: m)
  # map_x: 30 # (unit: m)
  # map_y: 30 # (unit: m)
  # map_z: 15 # (unit: m)
  # voxel_depth: 2
  # block_depth: 3
  resolution: 0.1 # (unit: m)
  map_x: 80 # (unit: m)
  map_y: 80 # (unit: m)
  map_z: 40 # (unit: m)
  voxel_depth: 1
  block_depth: 3
  near_distance_threshold: 8
  far_distance_threshold: 10

  sub_radius_ratio: 0.1
  voxel_radius_ratio: 0.1
  block_radius_ratio: 0.5

Probability:
  # p_hit: 0.65
  # p_miss: 0.35
  # p_min: 0.10
  # p_max: 0.97
  # p_occ: 0.80

  p_hit: 0.7
  p_miss: 0.4
  p_min: 0.12
  p_max: 0.97
  p_occ: 0.75

DepthCamera:
  # gridmap
  # height: 640
  # width: 480
  # fx: 392.365234375
  # fy: 392.365234375
  # cx: 320.01055908203125
  # cy: 241.12890625

  # tum
  # height: 480
  # width: 640
  # fx: 525.0
  # fy: 525.0
  # cx: 319.5
  # cy: 239.5

  # 仿真
  # height: 480
  # width: 640
  # fx: 554.3826904296875
  # fy: 554.3826904296875
  # cx: 320.0
  # cy: 240.0

  # uhuman
  height: 480
  width: 720
  fx: 415.69219381653056
  fy: 415.69219381653056
  cx: 360.0
  cy: 240.0

  k_depth_scaling_factor: 1000
  depth_maxdist: 40.0
  depth_mindist: 0.1
  depth_filter_margin: 10
  skip_pixel: 4
  min_valid_ratio: 0.3
  depth_threshold_subvoxel: 0.1           # 体素z距离与像素平均值距离比较阈值
  depth_threshold_voxel: 0.2        # 体素z距离与体素平均值距离比较阈值
  depth_threshold_block: 0.2            # 体素z距离与体素平均值距离比较阈值

  R_C_2_B: !!opencv-matrix #normal realsense
    rows: 3
    cols: 3
    dt: d
    data: [0, 0, 1, -1, 0, 0, 0, -1, 0]

  T_C_2_B: !!opencv-matrix
    rows: 1
    cols: 3
    dt: d
    data: [0.0, 0.0, 0.0]
