%YAML:1.2
---
OccMap:
  resolution: 0.2 # (unit: m)
<<<<<<< Updated upstream
  map_x: 160 # (unit: m)
  map_y: 160 # (unit: m)
=======
  map_x: 100 # (unit: m)
  map_y: 100 # (unit: m)
>>>>>>> Stashed changes
  map_z: 20 # (unit: m)
  voxel_depth: 1
  block_depth: 2
  near_distance_threshold: 40.0
  far_distance_threshold: 60.0

  min_valid_ratio_sub: 0.0
  min_valid_ratio_voxel: 0.0
  min_valid_ratio_block: 0.0

  min_valid_ratio_ratio: 0.1

  depth_threshold_subvoxel: 0.0    # 判断是否是否相较阈值
  depth_threshold_voxel: 0.0       
  depth_threshold_block: 0.0       

  sub_radius_ratio: 0.1
  voxel_radius_ratio: 0.1
  block_radius_ratio: 0.5

Probability:
  # p_hit: 0.65
  # p_miss: 0.35
  # p_min: 0.10
  # p_max: 0.97
  # p_occ: 0.80
  p_hit: 0.8
  p_miss: 0.4
  p_min: 0.12
  p_max: 0.97
  p_occ: 0.75

LiDAR:
<<<<<<< Updated upstream
  # 激光雷达参数 livox
=======
  # 激光雷达参数
>>>>>>> Stashed changes
  # fov_theta_range: [-35.2, 35.2]  # 水平视场角范围 (度)
  # fov_phi_range: [-38.7, 38.7]    # 垂直视场角范围 (度)
  # fov_depth: 60.0                  # 最大探测距离 (米)
  # sensor_res_hor: 0.2             # 水平分辨率 (度)
  # sensor_res_vert: 0.8            # 垂直分辨率 (度)
<<<<<<< Updated upstream
  # kitti
  fov_theta_range: [-180.0, 180.0]  # 水平视场角范围 (度)
  fov_phi_range: [-24.8, 2]    # 垂直视场角范围 (度)
  fov_depth: 120.0                  # 最大探测距离 (米)
  sensor_res_hor: 0.24            # 水平分辨率 (度)
=======

  fov_theta_range: [-45.0, 45.0]  # 水平视场角范围 (度)
  fov_phi_range: [-24.8, 2.0]    # 垂直视场角范围 (度)
  fov_depth: 120.0                  # 最大探测距离 (米)
  sensor_res_hor: 0.12            # 水平分辨率 (度)
>>>>>>> Stashed changes
  sensor_res_vert: 0.4            # 垂直分辨率 (度)
  
  # 处理参数
  depth_mindist: 0.1
  depth_filter_margin: 20
  skip_pixel: 4
  k_depth_scaling_factor: 1
  
  # 坐标系变换参数
  R_C_2_B: !!opencv-matrix #normal realsense
    rows: 3
    cols: 3
    dt: d
    data: [0, 0, 1, -1, 0, 0, 0, -1, 0]

  T_C_2_B: !!opencv-matrix
    rows: 1
    cols: 3
    dt: d
    data: [0.0, 0.0, 0.0]
